#!/usr/bin/env python3
"""Generate text/Phrases.lua from ua_table.tsv so the on-screen text and the audio
never drift apart.

Run:  python generation/build_action_text.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.dirname(HERE)
TABLE = os.path.join(HERE, "ua_table.tsv")
OUT = os.path.join(PACK, "text", "Phrases.lua")

HEADER = """-- Generated by generation/build_action_text.py from generation/ua_table.tsv.
-- Do not edit by hand.
local _, ns = ...

ns.phraseByVoice = {
"""


def rows():
    with open(TABLE, encoding="utf-8") as fh:
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 3 and parts[0].strip():
                yield parts[0].strip(), parts[2].strip()


def main():
    entries = sorted(rows())
    bad = [key for key, text in entries
           if any(c in field for field in (key, text) for c in ('"', "\\", "\r", "\n"))]
    if bad:
        print("rows with characters that need escaping: %s" % ", ".join(bad))
        return 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER)
        for key, text in entries:
            fh.write('\t["%s"] = "%s",\n' % (key, text))
        fh.write("}\n")
    print("%d phrases written to %s" % (len(entries), os.path.relpath(OUT, PACK)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
